name: build


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: s4u/maven-settings-action@v2
      with:
        servers: '[{"id": "vpro-ossrh", "username": "vpro", "password": "${{secrets.OSSRH_PASSWORD}}"}]'
    - name: Build with Maven
      run: mvn -B -fn -Pdeploy deploy
    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
      if: ${{ github.event_name == 'push' }}
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: ${{ github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
